name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter openpyxl pandas pyinstaller

    - name: Compilar con PyInstaller
      run: |
        pyinstaller --noconsole --onefile --collect-all customtkinter app.py

    - name: Subir ejecutable como Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CCTV-Weekly-Report-CFC-Windows
        path: dist/app.exe